MODEL SMALL
STACK
DATA SEGMENT
BLOCK DB 256 DUP(?)
MAX DB ?
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV SI, OFFSET BLOCK
    MOV AL, [SI]
    INC SI
    MOV CX, 255
NEXT:
    MOV BL, [SI]
    CMP BL, 0
    JGE FIND_MAX
    NEG BL
FIND_MAX:
    CMP AL, BL
    JGE DONE
    MOV AL, [SI]
DONE:
    INC SI
    LOOP NEXT
    MOV MAX, AL
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START